name: Plan and Execute Pipeline

on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Plan Phase
        run: java -cp target/plan-and-execute-java-1.0-SNAPSHOT.jar com.example.Plan

  execute:
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Execute Phase
        run: java -cp target/plan-and-execute-java-1.0-SNAPSHOT.jar com.example.Execute